############################################################
# AAU CNCS CS-Lab 3 Playbooks: Update system on Ubuntu 16.04
############################################################
---
- hosts: cslab3
  become: true
  become_method: sudo

  tasks:
    -  name: Update & Upgrade System
       shell: "apt-get update;apt-get upgrade -y"
