##################################################################
# AAU CNCS CS-Lab 3 Playbooks: Install virtualbox on Ubuntu 16.04
##################################################################
---
- hosts: cslab3
  become: true
  become_method: sudo

  tasks:
    - name: Install VirtualBox
      apt:
        name: virtualbox
        state: latest
        update_cache: yes
        install_recommends: yes
    - name: Install the build dependencies for package "virtualbox"
      apt:
        pkg: virtualbox
        state: build-dep
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
