############################################################
# AAU CNCS CS-Lab 3 Playbooks: Install Netbeans on Ubuntu 16.04
############################################################
---
- hosts: cslab3
  become: true
  become_method: sudo

  tasks:
    -   name: "Install Netbeans using SNAP classic"
        command: "sudo snap install netbeans --classic"

  # tasks:
  #   - name: Install Netbeans
  #     community.general.snap:
  #       - name: netbeans
  #       - classic: yes